- hosts: MySQL app gitlab runner monitoring
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    user
  roles:
   - InstaLL_Node_Exporter

  environment:
     http_proxy: http://emilsuleymanov.ru:8118
     https_proxy: http://emilsuleymanov.ru:8118
